name: Docker

on:
  workflow_run:
    workflows: ["build"]
    types: [requested]
    branches:
      - 'latest'
      - 'dev'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to Docker Hub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: |
            justsky/honeypots
            ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/honeypots:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/honeypots:buildcache,mode=max

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          #content: "Honeypots Docker image has been pushed to repo."
          title: "CI"
          description: "Build and pushed Docker image"
          color: 0x0000ff
          url: "https://github.com/just5ky/honeypots"
          username: GitHub Actions
          avatar_url: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/github.png